Repository BumgeunSong/Krello, pull requests merged in 2022-05, with the labels that each got.

#13 [Kai] Validator 기능 및 테스트 구현
  Krello.xcodeproj/project.pbxproj
  Krello/Model/Validator.swift
  KrelloTests/ValidatorTest.swift
Labels: Feature

#16 [Rosa] 로그인 화면의 키보드 UI 수정
  Krello.xcodeproj/project.pbxproj
  Krello/Controller/LoginView.swift
  Krello/Controller/LoginViewController.swift
  KrelloTests/LoginViewTest.swift
Labels: enhancement

#18 [Eddy] 고립된 테스트 환경을 위한 AppDelegate 로직 변경
  Krello.xcodeproj/project.pbxproj
  Krello.xcodeproj/xcshareddata/xcschemes/Krello.xcscheme
  Krello.xcodeproj/xcuserdata/bumgeunsong.xcuserdatad/xcschemes/xcschememanagement.plist
  Krello/Supporting/AppDelegate.swift
  Krello/Supporting/TestingAppDelegate.swift
  Krello/Supporting/main.swift
Labels: enhancement

#19 [Rosa] login view 터치했을때 키보드가 내려갔는지 테스트
  KrelloTests/LoginViewTest.swift
Labels: test

#20 [Kai] AuthenticationManger 추가
  Krello.xcodeproj/project.pbxproj
  Krello/Model/AuthenticationInfo.swift
  Krello/Model/UserInfo.swift
  Krello/Network/AuthenticationEngine.swift
  Krello/Network/AuthenticationManager.swift
  Krello/Supporting/main.swift
  KrelloTests/AuthenticationManagerIntegrationTest.swift
  KrelloTests/AuthenticationTest.swift
Labels: Feature

#28 [Rosa] Firestore 에서 데이터를 읽어오는 객체 구현 & BoardList 화면에 데이터 뿌리기
  Krello.xcodeproj/project.pbxproj
  Krello/BoardCRUD/Controller/BoardListViewController.swift
  Krello/BoardCRUD/Model/BoardManager.swift
  Krello/Login/Model/Firestore/FirestoreService.swift
  Krello/Supporting/Info.plist
  KrelloTests/FirestoreServiceTest.swift
  Podfile
  Podfile.lock
Labels: ⛏ enhancement

#44 [Kai & Rosa] 로그인, 회원가입 DB 연결, Scene delegate 을 활용한 화면이동 구현
  .github/workflows/buildAndTest.yml
  Krello.xcodeproj/project.pbxproj
  Krello.xcodeproj/xcshareddata/xcschemes/Krello.xcscheme
  Krello/BoardCRUD/Controller/BoardListViewController.swift
  Krello/Login/Controller/LoginViewController.swift
  Krello/Login/Model/Firestore/FirestoreService.swift
  Krello/Login/View/LoginView.swift
  Krello/Signup/Controller/SignupViewController.swift
  Krello/Signup/Model/Validator.swift
  Krello/Signup/View/SignupFormView.swift
  Krello/Supporting/SceneDelegate.swift
  KrelloTests/IntegrationTests/AuthenticationManagerIntegrationTest.swift
  KrelloTests/IntegrationTests/FirestoreServiceTest.swift
  KrelloTests/LoginViewTest.swift
Labels: ⛏ enhancement

#47 [Kai & Rosa] Eddy 피드백 수정
  Krello/BoardCRUD/Controller/BoardListViewController.swift
  Krello/BoardCRUD/Model/BoardManager.swift
  Krello/Login/Controller/LoginViewController.swift
  Krello/Signup/Controller/SignupViewController.swift
  Krello/Signup/Model/Validator.swift
  Krello/Supporting/SceneDelegate.swift
Labels: 🌈 refactoring
